development:
  secret_key_base: secret_key_base_is_not_used

test:
  secret_key_base: secret_key_base_is_not_used

production:
  secret_key_base: secret_key_base_is_not_used

qa:
  secret_key_base: secret_key_base_is_not_used

dev:
  secret_key_base: secret_key_base_is_not_used

